# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170629_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrecord',
            name='asset_number',
            field=models.IntegerField(null=True),
        ),
    ]
