# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_assetrecord_asset_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrecord',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
