# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-10 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_assetrecord_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(max_length=64, unique=True, verbose_name='sdsdsd'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP'),
        ),
    ]
