# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-10 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20170710_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(max_length=64, unique=True, verbose_name='主机名'),
        ),
    ]
